!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.15 (master) - 15 Apr 2020 11:54
!
MODULE LLT_MODULE_DIFF
  IMPLICIT NONE
  REAL, PARAMETER :: zero=0.0
  REAL, PARAMETER :: pi=3.1415926535897932384626
  REAL, PARAMETER :: eps=EPSILON(zero)

CONTAINS
!  Differentiation of induced_vel in forward (tangent) mode:
!   variations   of useful results: gamma_ind
!   with respect to varying inputs: xp x1 x2
  SUBROUTINE INDUCED_VEL_D(uinf, x1, x1d, x2, x2d, xp, xpd, gamma_ind, &
&   gamma_indd)
    IMPLICIT NONE
! Input variables
    REAL, INTENT(IN) :: uinf(3), x1(3), x2(3), xp(3)
    REAL, INTENT(IN) :: x1d(3), x2d(3), xpd(3)
! Output variables
    REAL, INTENT(OUT) :: gamma_ind(3)
    REAL, INTENT(OUT) :: gamma_indd(3)
! Working variables
    REAL :: r1(3), r2(3), v1(3), v2(3), v3(3)
    REAL :: r1d(3), r2d(3), v1d(3), v2d(3), v3d(3)
    REAL :: uinfcr1(3), uinfcr2(3), r1cr2(3)
    REAL :: uinfcr1d(3), uinfcr2d(3), r1cr2d(3)
    REAL :: r1m, r2m, uinfdr1, uinfdr2, r1dr2, den
    REAL :: r1md, r2md, uinfdr1d, uinfdr2d, r1dr2d, dend
    INTRINSIC ABS
    REAL :: abs0
    REAL, DIMENSION(3) :: dummyzerodiffd
    REAL, DIMENSION(3) :: dummyzerodiffd0
    REAL, DIMENSION(3) :: dummyzerodiffd1
    REAL, DIMENSION(3) :: dummyzerodiffd2
    REAL :: temp
    REAL, DIMENSION(3) :: temp0
! EXECUTION
! Compute vectors between the kinks and the point of interest
    r1d = xpd - x1d
    r1 = xp - x1
    r2d = xpd - x2d
    r2 = xp - x2
! Compute the magnitude of these vectors
    CALL NORM_D(r1, r1d, r1m, r1md)
    CALL NORM_D(r2, r2d, r2m, r2md)
! Compute cross products
    uinfcr1d = 0.0
    dummyzerodiffd = 0.0
    CALL CROSS_D(uinf, dummyzerodiffd, r1, r1d, uinfcr1, uinfcr1d)
    uinfcr2d = 0.0
    dummyzerodiffd0 = 0.0
    CALL CROSS_D(uinf, dummyzerodiffd0, r2, r2d, uinfcr2, uinfcr2d)
    r1cr2d = 0.0
    CALL CROSS_D(r1, r1d, r2, r2d, r1cr2, r1cr2d)
! Compute dot products
    dummyzerodiffd1 = 0.0
    CALL DOT_D(uinf, dummyzerodiffd1, r1, r1d, uinfdr1, uinfdr1d)
    dummyzerodiffd2 = 0.0
    CALL DOT_D(uinf, dummyzerodiffd2, r2, r2d, uinfdr2, uinfdr2d)
    CALL DOT_D(r1, r1d, r2, r2d, r1dr2, r1dr2d)
! Compute contributions of each vortex segment
    temp = r2m*(r2m-uinfdr2)
    v1d = (uinfcr2d-uinfcr2*((r2m-uinfdr2)*r2md+r2m*(r2md-uinfdr2d))/&
&     temp)/temp
    v1 = uinfcr2/temp
    dend = r2m*r1md + r1m*r2md + r1dr2d
    den = r1m*r2m + r1dr2
    IF (den .GE. 0.) THEN
      abs0 = den
    ELSE
      abs0 = -den
    END IF
    IF (abs0 .GT. eps) THEN
      temp = r1m*r2m*den
      temp0 = (r1m+r2m)*r1cr2/temp
      v2d = (r1cr2*(r1md+r2md)+(r1m+r2m)*r1cr2d-temp0*(den*(r2m*r1md+r1m&
&       *r2md)+r1m*r2m*dend))/temp
      v2 = temp0
    ELSE
! Bound vortex induces no velocity along its length
      v2 = zero
      v2d = 0.0
    END IF
    temp = r1m*(r1m-uinfdr1)
    v3d = -((uinfcr1d-uinfcr1*((r1m-uinfdr1)*r1md+r1m*(r1md-uinfdr1d))/&
&     temp)/temp)
    v3 = -(uinfcr1/temp)
! Compute overall induced velocity (without the circulation: V/gamma)
    gamma_indd = 0.25*(v1d+v2d+v3d)/pi
    gamma_ind = 0.25*(v1+v2+v3)/pi
  END SUBROUTINE INDUCED_VEL_D

!  Differentiation of induced_vel in reverse (adjoint) mode:
!   gradient     of useful results: xp gamma_ind
!   with respect to varying inputs: xp x1 x2
  SUBROUTINE INDUCED_VEL_B(uinf, x1, x1b, x2, x2b, xp, xpb, gamma_ind, &
&   gamma_indb)
    IMPLICIT NONE
! Input variables
    REAL, INTENT(IN) :: uinf(3), x1(3), x2(3), xp(3)
    REAL :: x1b(3), x2b(3), xpb(3)
! Output variables
    REAL :: gamma_ind(3)
    REAL :: gamma_indb(3)
! Working variables
    REAL :: r1(3), r2(3), v1(3), v2(3), v3(3)
    REAL :: r1b(3), r2b(3), v1b(3), v2b(3), v3b(3)
    REAL :: uinfcr1(3), uinfcr2(3), r1cr2(3)
    REAL :: uinfcr1b(3), uinfcr2b(3), r1cr2b(3)
    REAL :: r1m, r2m, uinfdr1, uinfdr2, r1dr2, den
    REAL :: r1mb, r2mb, uinfdr1b, uinfdr2b, r1dr2b, denb
    INTRINSIC ABS
    REAL :: abs0
    REAL :: temp
    REAL :: tempb
    REAL, DIMENSION(3) :: tempb0
    REAL :: temp0
    REAL :: tempb1
    INTEGER :: branch
    REAL :: uinfb(3)
! EXECUTION
! Compute vectors between the kinks and the point of interest
    r1 = xp - x1
    r2 = xp - x2
! Compute the magnitude of these vectors
    CALL NORM(r1, r1m)
    CALL NORM(r2, r2m)
! Compute cross products
    CALL CROSS(uinf, r1, uinfcr1)
    CALL CROSS(uinf, r2, uinfcr2)
    CALL CROSS(r1, r2, r1cr2)
! Compute dot products
    CALL DOT(uinf, r1, uinfdr1)
    CALL DOT(uinf, r2, uinfdr2)
    CALL DOT(r1, r2, r1dr2)
! Compute contributions of each vortex segment
    v1 = uinfcr2/r2m/(r2m-uinfdr2)
    den = r1m*r2m + r1dr2
    IF (den .GE. 0.) THEN
      abs0 = den
      CALL PUSHCONTROL1B(0)
    ELSE
      abs0 = -den
      CALL PUSHCONTROL1B(1)
    END IF
    IF (abs0 .GT. eps) THEN
      v2 = (r1m+r2m)*r1cr2/r1m/r2m/den
      CALL PUSHCONTROL1B(0)
    ELSE
! Bound vortex induces no velocity along its length
      v2 = zero
      CALL PUSHCONTROL1B(1)
    END IF
    v3 = -(uinfcr1/r1m/(r1m-uinfdr1))
! Compute overall induced velocity (without the circulation: V/gamma)
    gamma_ind = 0.25*(v1+v2+v3)/pi
    v1b = 0.0
    v2b = 0.0
    v3b = 0.0
    tempb0 = 0.25*gamma_indb/pi
    v1b = tempb0
    v2b = tempb0
    v3b = tempb0
    uinfcr1b = 0.0
    temp0 = r1m*(r1m-uinfdr1)
    uinfcr1b = -(v3b/temp0)
    tempb1 = SUM(uinfcr1*v3b)/temp0**2
    r1mb = (2*r1m-uinfdr1)*tempb1
    uinfdr1b = -(r1m*tempb1)
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      r1cr2b = 0.0
      temp = r1m*r2m*den
      tempb0 = v2b/temp
      tempb1 = SUM(r1cr2*tempb0)
      r1cr2b = (r1m+r2m)*tempb0
      tempb = -(SUM(r1cr2*tempb0)*(r1m+r2m)/temp)
      r1mb = r1mb + r2m*den*tempb + tempb1
      r2mb = r1m*den*tempb + tempb1
      denb = r1m*r2m*tempb
    ELSE
      r2mb = 0.0
      denb = 0.0
      r1cr2b = 0.0
    END IF
    CALL POPCONTROL1B(branch)
    temp = r2m*(r2m-uinfdr2)
    tempb = -(SUM(uinfcr2*v1b)/temp**2)
    r1mb = r1mb + r2m*denb
    r2mb = r2mb + r1m*denb + (2*r2m-uinfdr2)*tempb
    r1dr2b = denb
    uinfcr2b = 0.0
    uinfcr2b = v1b/temp
    uinfdr2b = -(r2m*tempb)
    r1b = 0.0
    r2b = 0.0
    CALL DOT_B(r1, r1b, r2, r2b, r1dr2, r1dr2b)
    uinfb = 0.0
    CALL DOT_B(uinf, uinfb, r2, r2b, uinfdr2, uinfdr2b)
    uinfb = 0.0
    CALL DOT_B(uinf, uinfb, r1, r1b, uinfdr1, uinfdr1b)
    CALL CROSS_B(r1, r1b, r2, r2b, r1cr2, r1cr2b)
    uinfb = 0.0
    CALL CROSS_B(uinf, uinfb, r2, r2b, uinfcr2, uinfcr2b)
    uinfb = 0.0
    CALL CROSS_B(uinf, uinfb, r1, r1b, uinfcr1, uinfcr1b)
    CALL NORM_B(r2, r2b, r2m, r2mb)
    CALL NORM_B(r1, r1b, r1m, r1mb)
    x2b = 0.0
    xpb = xpb + r2b + r1b
    x2b = -r2b
    x1b = 0.0
    x1b = -r1b
  END SUBROUTINE INDUCED_VEL_B

  SUBROUTINE INDUCED_VEL(uinf, x1, x2, xp, gamma_ind)
    IMPLICIT NONE
! Input variables
    REAL, INTENT(IN) :: uinf(3), x1(3), x2(3), xp(3)
! Output variables
    REAL, INTENT(OUT) :: gamma_ind(3)
! Working variables
    REAL :: r1(3), r2(3), v1(3), v2(3), v3(3)
    REAL :: uinfcr1(3), uinfcr2(3), r1cr2(3)
    REAL :: r1m, r2m, uinfdr1, uinfdr2, r1dr2, den
    INTRINSIC ABS
    REAL :: abs0
! EXECUTION
! Compute vectors between the kinks and the point of interest
    r1 = xp - x1
    r2 = xp - x2
! Compute the magnitude of these vectors
    CALL NORM(r1, r1m)
    CALL NORM(r2, r2m)
! Compute cross products
    CALL CROSS(uinf, r1, uinfcr1)
    CALL CROSS(uinf, r2, uinfcr2)
    CALL CROSS(r1, r2, r1cr2)
! Compute dot products
    CALL DOT(uinf, r1, uinfdr1)
    CALL DOT(uinf, r2, uinfdr2)
    CALL DOT(r1, r2, r1dr2)
! Compute contributions of each vortex segment
    v1 = uinfcr2/r2m/(r2m-uinfdr2)
    den = r1m*r2m + r1dr2
    IF (den .GE. 0.) THEN
      abs0 = den
    ELSE
      abs0 = -den
    END IF
    IF (abs0 .GT. eps) THEN
      v2 = (r1m+r2m)*r1cr2/r1m/r2m/den
    ELSE
! Bound vortex induces no velocity along its length
      v2 = zero
    END IF
    v3 = -(uinfcr1/r1m/(r1m-uinfdr1))
! Compute overall induced velocity (without the circulation: V/gamma)
    gamma_ind = 0.25*(v1+v2+v3)/pi
  END SUBROUTINE INDUCED_VEL

!  Differentiation of get_aic_matrix in forward (tangent) mode:
!   variations   of useful results: aic
!   with respect to varying inputs: x
!============================================================
  SUBROUTINE GET_AIC_MATRIX_D(n_vort, x, xd, uinf, aic, aicd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: xd(3, n_vort+1)
    REAL, INTENT(IN) :: uinf(3)
! Output variables
    REAL, INTENT(OUT) :: aic(3, n_vort, n_vort)
    REAL, INTENT(OUT) :: aicd(3, n_vort, n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: x1(3), x2(3), xcen(3), gamma_ind(3), ni(3)
    REAL :: x1d(3), x2d(3), xcend(3), gamma_indd(3)
    REAL :: nim, sim
    aicd = 0.0
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      x1d = xd(:, ii)
      x1 = x(:, ii)
      x2d = xd(:, ii+1)
      x2 = x(:, ii+1)
! Compute the center of the bound vortex
      xcend = 0.5*(x1d+x2d)
      xcen = 0.5*(x1+x2)
! Loop over all bound vortices to compute the influence coefficients
      DO jj=1,n_vort
! Get kink coordinates of the current vortex
        x1d = xd(:, jj)
        x1 = x(:, jj)
        x2d = xd(:, jj+1)
        x2 = x(:, jj+1)
! The induced velocity, normalized by gamma, is the influence
! coefficient.
        CALL INDUCED_VEL_D(uinf, x1, x1d, x2, x2d, xcen, xcend, &
&                    gamma_ind, gamma_indd)
        aicd(:, jj, ii) = gamma_indd
        aic(:, jj, ii) = gamma_ind
      END DO
    END DO
  END SUBROUTINE GET_AIC_MATRIX_D

!  Differentiation of get_aic_matrix in reverse (adjoint) mode:
!   gradient     of useful results: x aic
!   with respect to varying inputs: x
!============================================================
  SUBROUTINE GET_AIC_MATRIX_B(n_vort, x, xb, uinf, aic, aicb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL :: xb(3, n_vort+1)
    REAL, INTENT(IN) :: uinf(3)
! Output variables
    REAL :: aic(3, n_vort, n_vort)
    REAL :: aicb(3, n_vort, n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: x1(3), x2(3), xcen(3), gamma_ind(3), ni(3)
    REAL :: x1b(3), x2b(3), xcenb(3), gamma_indb(3)
    REAL :: nim, sim
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      CALL PUSHREAL4ARRAY(x1, 3)
      x1 = x(:, ii)
      CALL PUSHREAL4ARRAY(x2, 3)
      x2 = x(:, ii+1)
! Compute the center of the bound vortex
      CALL PUSHREAL4ARRAY(xcen, 3)
      xcen = 0.5*(x1+x2)
! Loop over all bound vortices to compute the influence coefficients
      DO jj=1,n_vort
! Get kink coordinates of the current vortex
        CALL PUSHREAL4ARRAY(x1, 3)
        x1 = x(:, jj)
        CALL PUSHREAL4ARRAY(x2, 3)
        x2 = x(:, jj+1)
! The induced velocity, normalized by gamma, is the influence
! coefficient.
        CALL INDUCED_VEL(uinf, x1, x2, xcen, gamma_ind)
        aic(:, jj, ii) = gamma_ind
      END DO
    END DO
    DO ii=n_vort,1,-1
      xcenb = 0.0
      DO jj=n_vort,1,-1
        gamma_indb = 0.0
        gamma_indb = aicb(:, jj, ii)
        aicb(:, jj, ii) = 0.0
        CALL INDUCED_VEL_B(uinf, x1, x1b, x2, x2b, xcen, xcenb, &
&                    gamma_ind, gamma_indb)
        CALL POPREAL4ARRAY(x2, 3)
        xb(:, jj+1) = xb(:, jj+1) + x2b
        CALL POPREAL4ARRAY(x1, 3)
        xb(:, jj) = xb(:, jj) + x1b
      END DO
      x1b = 0.0
      x2b = 0.0
      CALL POPREAL4ARRAY(xcen, 3)
      x1b = 0.5*xcenb
      x2b = 0.5*xcenb
      CALL POPREAL4ARRAY(x2, 3)
      xb(:, ii+1) = xb(:, ii+1) + x2b
      CALL POPREAL4ARRAY(x1, 3)
      xb(:, ii) = xb(:, ii) + x1b
    END DO
  END SUBROUTINE GET_AIC_MATRIX_B

!============================================================
  SUBROUTINE GET_AIC_MATRIX(n_vort, x, uinf, aic)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: uinf(3)
! Output variables
    REAL, INTENT(OUT) :: aic(3, n_vort, n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: x1(3), x2(3), xcen(3), gamma_ind(3), ni(3)
    REAL :: nim, sim
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      x1 = x(:, ii)
      x2 = x(:, ii+1)
! Compute the center of the bound vortex
      xcen = 0.5*(x1+x2)
! Loop over all bound vortices to compute the influence coefficients
      DO jj=1,n_vort
! Get kink coordinates of the current vortex
        x1 = x(:, jj)
        x2 = x(:, jj+1)
! The induced velocity, normalized by gamma, is the influence
! coefficient.
        CALL INDUCED_VEL(uinf, x1, x2, xcen, gamma_ind)
        aic(:, jj, ii) = gamma_ind
      END DO
    END DO
  END SUBROUTINE GET_AIC_MATRIX

!  Differentiation of get_geom_vectors in forward (tangent) mode:
!   variations   of useful results: uai uni si areas
!   with respect to varying inputs: alpha0 x
!============================================================
  SUBROUTINE GET_GEOM_VECTORS_D(n_vort, x, xd, alpha0, alpha0d, chords, &
&   uai, uaid, uni, unid, si, sid, areas, areasd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: xd(3, n_vort+1)
    REAL, INTENT(IN) :: alpha0(n_vort), chords(n_vort)
    REAL, INTENT(IN) :: alpha0d(n_vort)
! Output variables
    REAL, INTENT(OUT) :: uai(3, n_vort), uni(3, n_vort)
    REAL, INTENT(OUT) :: uaid(3, n_vort), unid(3, n_vort)
    REAL, INTENT(OUT) :: si(3, n_vort), areas(n_vort)
    REAL, INTENT(OUT) :: sid(3, n_vort), areasd(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: x1(3), x2(3), usi(3), ni(3)
    REAL :: x1d(3), x2d(3), usid(3), nid(3)
    REAL :: nim, sim
    REAL :: nimd, simd
    INTRINSIC COS
    INTRINSIC SIN
    uaid = 0.0
    unid = 0.0
    sid = 0.0
    areasd = 0.0
    nid = 0.0
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      x1d = xd(:, ii)
      x1 = x(:, ii)
      x2d = xd(:, ii+1)
      x2 = x(:, ii+1)
! Compute the vector along the local span
      sid(:, ii) = x2d - x1d
      si(:, ii) = x2 - x1
      CALL NORMALIZE_D(si(:, ii), sid(:, ii), usi, usid)
! Create a unitary vector along the chordline
! pointing to the trailing edge
      uaid(1, ii) = -(SIN(alpha0(ii))*alpha0d(ii))
      uai(1, ii) = COS(alpha0(ii))
      uaid(2, ii) = 0.0
      uai(2, ii) = zero
      uaid(3, ii) = -(COS(alpha0(ii))*alpha0d(ii))
      uai(3, ii) = -SIN(alpha0(ii))
! Get the normal vector as the normal between the span
! and the chord vector
      CALL CROSS_D(uai(:, ii), uaid(:, ii), usi, usid, ni, nid)
      CALL NORMALIZE_D(ni, nid, uni(:, ii), unid(:, ii))
! Compute the local area of the panel.
! The norm of the normal vector is the sine of the angle.
      CALL NORM_D(ni, nid, nim, nimd)
      CALL NORM_D(si(:, ii), sid(:, ii), sim, simd)
      areasd(ii) = chords(ii)*(sim*nimd+nim*simd)
      areas(ii) = nim*chords(ii)*sim
    END DO
  END SUBROUTINE GET_GEOM_VECTORS_D

!  Differentiation of get_geom_vectors in reverse (adjoint) mode:
!   gradient     of useful results: alpha0 x uai uni si areas
!   with respect to varying inputs: alpha0 x
!============================================================
  SUBROUTINE GET_GEOM_VECTORS_B(n_vort, x, xb, alpha0, alpha0b, chords, &
&   uai, uaib, uni, unib, si, sib, areas, areasb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL :: xb(3, n_vort+1)
    REAL, INTENT(IN) :: alpha0(n_vort), chords(n_vort)
    REAL :: alpha0b(n_vort)
! Output variables
    REAL :: uai(3, n_vort), uni(3, n_vort)
    REAL :: uaib(3, n_vort), unib(3, n_vort)
    REAL :: si(3, n_vort), areas(n_vort)
    REAL :: sib(3, n_vort), areasb(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: x1(3), x2(3), usi(3), ni(3)
    REAL :: x1b(3), x2b(3), usib(3), nib(3)
    REAL :: nim, sim
    REAL :: nimb, simb
    INTRINSIC COS
    INTRINSIC SIN
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      x1 = x(:, ii)
      x2 = x(:, ii+1)
! Compute the vector along the local span
      si(:, ii) = x2 - x1
      CALL PUSHREAL4ARRAY(usi, 3)
      CALL NORMALIZE(si(:, ii), usi)
! Create a unitary vector along the chordline
! pointing to the trailing edge
      uai(1, ii) = COS(alpha0(ii))
      uai(2, ii) = zero
      uai(3, ii) = -SIN(alpha0(ii))
! Get the normal vector as the normal between the span
! and the chord vector
      CALL PUSHREAL4ARRAY(ni, 3)
      CALL CROSS(uai(:, ii), usi, ni)
      CALL NORMALIZE(ni, uni(:, ii))
! Compute the local area of the panel.
! The norm of the normal vector is the sine of the angle.
      CALL PUSHREAL4(nim)
      CALL NORM(ni, nim)
      CALL PUSHREAL4(sim)
      CALL NORM(si(:, ii), sim)
      areas(ii) = nim*chords(ii)*sim
    END DO
    nib = 0.0
    DO ii=n_vort,1,-1
      nimb = sim*chords(ii)*areasb(ii)
      simb = nim*chords(ii)*areasb(ii)
      areasb(ii) = 0.0
      CALL POPREAL4(sim)
      CALL NORM_B(si(:, ii), sib(:, ii), sim, simb)
      CALL POPREAL4(nim)
      CALL NORM_B(ni, nib, nim, nimb)
      CALL NORMALIZE_B(ni, nib, uni(:, ii), unib(:, ii))
      unib(:, ii) = 0.0
      CALL POPREAL4ARRAY(ni, 3)
      usib = 0.0
      CALL CROSS_B(uai(:, ii), uaib(:, ii), usi, usib, ni, nib)
      alpha0b(ii) = alpha0b(ii) - COS(alpha0(ii))*uaib(3, ii) - SIN(&
&       alpha0(ii))*uaib(1, ii)
      uaib(3, ii) = 0.0
      uaib(2, ii) = 0.0
      uaib(1, ii) = 0.0
      CALL POPREAL4ARRAY(usi, 3)
      CALL NORMALIZE_B(si(:, ii), sib(:, ii), usi, usib)
      x1b = 0.0
      x2b = 0.0
      x2b = sib(:, ii)
      x1b = -sib(:, ii)
      sib(:, ii) = 0.0
      xb(:, ii+1) = xb(:, ii+1) + x2b
      xb(:, ii) = xb(:, ii) + x1b
    END DO
  END SUBROUTINE GET_GEOM_VECTORS_B

!============================================================
  SUBROUTINE GET_GEOM_VECTORS(n_vort, x, alpha0, chords, uai, uni, si, &
&   areas)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: alpha0(n_vort), chords(n_vort)
! Output variables
    REAL, INTENT(OUT) :: uai(3, n_vort), uni(3, n_vort)
    REAL, INTENT(OUT) :: si(3, n_vort), areas(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: x1(3), x2(3), usi(3), ni(3)
    REAL :: nim, sim
    INTRINSIC COS
    INTRINSIC SIN
! EXECUTION
! Loop over all vortices
    DO ii=1,n_vort
! Get kink coordinates of the current vortex
      x1 = x(:, ii)
      x2 = x(:, ii+1)
! Compute the vector along the local span
      si(:, ii) = x2 - x1
      CALL NORMALIZE(si(:, ii), usi)
! Create a unitary vector along the chordline
! pointing to the trailing edge
      uai(1, ii) = COS(alpha0(ii))
      uai(2, ii) = zero
      uai(3, ii) = -SIN(alpha0(ii))
! Get the normal vector as the normal between the span
! and the chord vector
      CALL CROSS(uai(:, ii), usi, ni)
      CALL NORMALIZE(ni, uni(:, ii))
! Compute the local area of the panel.
! The norm of the normal vector is the sine of the angle.
      CALL NORM(ni, nim)
      CALL NORM(si(:, ii), sim)
      areas(ii) = nim*chords(ii)*sim
    END DO
  END SUBROUTINE GET_GEOM_VECTORS

!  Differentiation of get_local_vels in forward (tangent) mode:
!   variations   of useful results: vlocal alphalocal
!   with respect to varying inputs: uai uni gama aic
!============================================================
  SUBROUTINE GET_LOCAL_VELS_D(n_vort, gama, gamad, aic, aicd, vinf, uai&
&   , uaid, uni, unid, vlocal, vlocald, alphalocal, alphalocald)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: gama(n_vort), aic(3, n_vort, n_vort)
    REAL, INTENT(IN) :: gamad(n_vort), aicd(3, n_vort, n_vort)
    REAL, INTENT(IN) :: vinf(3), uai(3, n_vort), uni(3, n_vort)
    REAL, INTENT(IN) :: uaid(3, n_vort), unid(3, n_vort)
! Output variables
    REAL, INTENT(OUT) :: vlocal(3, n_vort), alphalocal(n_vort)
    REAL, INTENT(OUT) :: vlocald(3, n_vort), alphalocald(n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: num, den
    REAL :: numd, dend
    INTRINSIC ATAN
    REAL :: temp
    vlocald = 0.0
    alphalocald = 0.0
! EXECUTION
! Do the matrix operation
    DO ii=1,n_vort
! Start with the free-strem contribution
      vlocald(:, ii) = 0.0
      vlocal(:, ii) = vinf
! Now add the velocities induced by each vortex
      DO jj=1,n_vort
        vlocald(:, ii) = vlocald(:, ii) + gama(jj)*aicd(:, jj, ii) + aic&
&         (:, jj, ii)*gamad(jj)
        vlocal(:, ii) = vlocal(:, ii) + aic(:, jj, ii)*gama(jj)
      END DO
! Compute the local angle of attack
      CALL DOT_D(vlocal(:, ii), vlocald(:, ii), uni(:, ii), unid(:, ii)&
&          , num, numd)
      CALL DOT_D(vlocal(:, ii), vlocald(:, ii), uai(:, ii), uaid(:, ii)&
&          , den, dend)
      temp = num/den
      alphalocald(ii) = (numd-temp*dend)/((1.0+temp**2)*den)
      alphalocal(ii) = ATAN(temp)
    END DO
  END SUBROUTINE GET_LOCAL_VELS_D

!  Differentiation of get_local_vels in reverse (adjoint) mode:
!   gradient     of useful results: vlocal gama alphalocal
!   with respect to varying inputs: uai uni gama aic
!============================================================
  SUBROUTINE GET_LOCAL_VELS_B(n_vort, gama, gamab, aic, aicb, vinf, uai&
&   , uaib, uni, unib, vlocal, vlocalb, alphalocal, alphalocalb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: gama(n_vort), aic(3, n_vort, n_vort)
    REAL :: gamab(n_vort), aicb(3, n_vort, n_vort)
    REAL, INTENT(IN) :: vinf(3), uai(3, n_vort), uni(3, n_vort)
    REAL :: uaib(3, n_vort), unib(3, n_vort)
! Output variables
    REAL :: vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: vlocalb(3, n_vort), alphalocalb(n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: num, den
    REAL :: numb, denb
    INTRINSIC ATAN
    REAL :: tempb
! EXECUTION
! Do the matrix operation
    DO ii=1,n_vort
! Start with the free-strem contribution
      vlocal(:, ii) = vinf
! Now add the velocities induced by each vortex
      DO jj=1,n_vort
        vlocal(:, ii) = vlocal(:, ii) + aic(:, jj, ii)*gama(jj)
      END DO
! Compute the local angle of attack
      CALL PUSHREAL4(num)
      CALL DOT(vlocal(:, ii), uni(:, ii), num)
      CALL PUSHREAL4(den)
      CALL DOT(vlocal(:, ii), uai(:, ii), den)
      alphalocal(ii) = ATAN(num/den)
    END DO
    uaib = 0.0
    unib = 0.0
    aicb = 0.0
    DO ii=n_vort,1,-1
      tempb = alphalocalb(ii)/(den*(1.0+(num/den)**2))
      alphalocalb(ii) = 0.0
      numb = tempb
      denb = -(num*tempb/den)
      CALL POPREAL4(den)
      CALL DOT_B(vlocal(:, ii), vlocalb(:, ii), uai(:, ii), uaib(:, ii)&
&          , den, denb)
      CALL POPREAL4(num)
      CALL DOT_B(vlocal(:, ii), vlocalb(:, ii), uni(:, ii), unib(:, ii)&
&          , num, numb)
      DO jj=n_vort,1,-1
        aicb(:, jj, ii) = aicb(:, jj, ii) + gama(jj)*vlocalb(:, ii)
        gamab(jj) = gamab(jj) + SUM(aic(:, jj, ii)*vlocalb(:, ii))
      END DO
      vlocalb(:, ii) = 0.0
    END DO
  END SUBROUTINE GET_LOCAL_VELS_B

!============================================================
  SUBROUTINE GET_LOCAL_VELS(n_vort, gama, aic, vinf, uai, uni, vlocal, &
&   alphalocal)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: gama(n_vort), aic(3, n_vort, n_vort)
    REAL, INTENT(IN) :: vinf(3), uai(3, n_vort), uni(3, n_vort)
! Output variables
    REAL, INTENT(OUT) :: vlocal(3, n_vort), alphalocal(n_vort)
! Working variables
    INTEGER :: ii, jj
    REAL :: num, den
    INTRINSIC ATAN
! EXECUTION
! Do the matrix operation
    DO ii=1,n_vort
! Start with the free-strem contribution
      vlocal(:, ii) = vinf
! Now add the velocities induced by each vortex
      DO jj=1,n_vort
        vlocal(:, ii) = vlocal(:, ii) + aic(:, jj, ii)*gama(jj)
      END DO
! Compute the local angle of attack
      CALL DOT(vlocal(:, ii), uni(:, ii), num)
      CALL DOT(vlocal(:, ii), uai(:, ii), den)
      alphalocal(ii) = ATAN(num/den)
    END DO
  END SUBROUTINE GET_LOCAL_VELS

!  Differentiation of compute_circulation_forces in forward (tangent) mode:
!   variations   of useful results: fcirc
!   with respect to varying inputs: vlocal gama si
!============================================================
  SUBROUTINE COMPUTE_CIRCULATION_FORCES_D(n_vort, rho, vlocal, vlocald, &
&   si, sid, gama, gamad, fcirc, fcircd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, vlocal(3, n_vort), si(3, n_vort)
    REAL, INTENT(IN) :: vlocald(3, n_vort), sid(3, n_vort)
    REAL, INTENT(IN) :: gama(n_vort)
    REAL, INTENT(IN) :: gamad(n_vort)
! Output variables
    REAL, INTENT(OUT) :: fcirc(3, n_vort)
    REAL, INTENT(OUT) :: fcircd(3, n_vort)
! Working variables
    INTEGER :: ii
    REAL :: li(3)
    REAL :: lid(3)
    fcircd = 0.0
    lid = 0.0
! EXECUTION
    DO ii=1,n_vort
! L=rho*V*gamma*l
      CALL CROSS_D(vlocal(:, ii), vlocald(:, ii), si(:, ii), sid(:, ii)&
&            , li, lid)
      fcircd(:, ii) = rho*(li*gamad(ii)+gama(ii)*lid)
      fcirc(:, ii) = rho*gama(ii)*li
    END DO
  END SUBROUTINE COMPUTE_CIRCULATION_FORCES_D

!  Differentiation of compute_circulation_forces in reverse (adjoint) mode:
!   gradient     of useful results: vlocal gama si fcirc
!   with respect to varying inputs: vlocal gama si
!============================================================
  SUBROUTINE COMPUTE_CIRCULATION_FORCES_B(n_vort, rho, vlocal, vlocalb, &
&   si, sib, gama, gamab, fcirc, fcircb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, vlocal(3, n_vort), si(3, n_vort)
    REAL :: vlocalb(3, n_vort), sib(3, n_vort)
    REAL, INTENT(IN) :: gama(n_vort)
    REAL :: gamab(n_vort)
! Output variables
    REAL :: fcirc(3, n_vort)
    REAL :: fcircb(3, n_vort)
! Working variables
    INTEGER :: ii
    REAL :: li(3)
    REAL :: lib(3)
! EXECUTION
    DO ii=1,n_vort
! L=rho*V*gamma*l
      CALL PUSHREAL4ARRAY(li, 3)
      CALL CROSS(vlocal(:, ii), si(:, ii), li)
      fcirc(:, ii) = rho*gama(ii)*li
    END DO
    lib = 0.0
    DO ii=n_vort,1,-1
      gamab(ii) = gamab(ii) + SUM(li*fcircb(:, ii))*rho
      lib = lib + gama(ii)*rho*fcircb(:, ii)
      fcircb(:, ii) = 0.0
      CALL POPREAL4ARRAY(li, 3)
      CALL CROSS_B(vlocal(:, ii), vlocalb(:, ii), si(:, ii), sib(:, ii)&
&            , li, lib)
    END DO
  END SUBROUTINE COMPUTE_CIRCULATION_FORCES_B

!============================================================
  SUBROUTINE COMPUTE_CIRCULATION_FORCES(n_vort, rho, vlocal, si, gama, &
&   fcirc)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, vlocal(3, n_vort), si(3, n_vort)
    REAL, INTENT(IN) :: gama(n_vort)
! Output variables
    REAL, INTENT(OUT) :: fcirc(3, n_vort)
! Working variables
    INTEGER :: ii
    REAL :: li(3)
! EXECUTION
    DO ii=1,n_vort
! L=rho*V*gamma*l
      CALL CROSS(vlocal(:, ii), si(:, ii), li)
      fcirc(:, ii) = rho*gama(ii)*li
    END DO
  END SUBROUTINE COMPUTE_CIRCULATION_FORCES

!  Differentiation of compute_airfoil_forces in forward (tangent) mode:
!   variations   of useful results: fairf
!   with respect to varying inputs: vlocal si areas alphalocal
!============================================================
  SUBROUTINE COMPUTE_AIRFOIL_FORCES_D(n_vort, rho, cl0, cla, areas, &
&   areasd, vlocal, vlocald, alphalocal, alphalocald, si, sid, fairf, &
&   fairfd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, cl0(n_vort), cla(n_vort), areas(n_vort)
    REAL, INTENT(IN) :: areasd(n_vort)
    REAL, INTENT(IN) :: vlocal(3, n_vort), alphalocal(n_vort), si(3, &
&   n_vort)
    REAL, INTENT(IN) :: vlocald(3, n_vort), alphalocald(n_vort), sid(3, &
&   n_vort)
! Output variables
    REAL, INTENT(OUT) :: fairf(3, n_vort)
    REAL, INTENT(OUT) :: fairfd(3, n_vort)
! Working variables
    REAL :: fairfm, cl, li(3), uli(3), vlocalm
    REAL :: fairfmd, cld, lid(3), ulid(3), vlocalmd
    INTEGER :: ii
    fairfd = 0.0
    lid = 0.0
! EXECUTION
! Loop over all horseshoe vortices
    DO ii=1,n_vort
! Compute the magnitude of the force given by the 2D section
! L = 0.5*Vlocal²*area*cl
      cld = cla(ii)*alphalocald(ii)
      cl = cl0(ii) + alphalocal(ii)*cla(ii)
      CALL NORM_D(vlocal(:, ii), vlocald(:, ii), vlocalm, vlocalmd)
      fairfmd = rho*0.5*(areas(ii)*cl*2*vlocalm*vlocalmd+vlocalm**2*(cl*&
&       areasd(ii)+areas(ii)*cld))
      fairfm = 0.5*rho*vlocalm*vlocalm*areas(ii)*cl
! Get normalized lift direction
      CALL CROSS_D(vlocal(:, ii), vlocald(:, ii), si(:, ii), sid(:, ii)&
&            , li, lid)
      CALL NORMALIZE_D(li, lid, uli, ulid)
! Store the force
      fairfd(:, ii) = uli*fairfmd + fairfm*ulid
      fairf(:, ii) = fairfm*uli
    END DO
  END SUBROUTINE COMPUTE_AIRFOIL_FORCES_D

!  Differentiation of compute_airfoil_forces in reverse (adjoint) mode:
!   gradient     of useful results: fairf
!   with respect to varying inputs: vlocal si areas alphalocal
!============================================================
  SUBROUTINE COMPUTE_AIRFOIL_FORCES_B(n_vort, rho, cl0, cla, areas, &
&   areasb, vlocal, vlocalb, alphalocal, alphalocalb, si, sib, fairf, &
&   fairfb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, cl0(n_vort), cla(n_vort), areas(n_vort)
    REAL :: areasb(n_vort)
    REAL, INTENT(IN) :: vlocal(3, n_vort), alphalocal(n_vort), si(3, &
&   n_vort)
    REAL :: vlocalb(3, n_vort), alphalocalb(n_vort), sib(3, n_vort)
! Output variables
    REAL :: fairf(3, n_vort)
    REAL :: fairfb(3, n_vort)
! Working variables
    REAL :: fairfm, cl, li(3), uli(3), vlocalm
    REAL :: fairfmb, clb, lib(3), ulib(3), vlocalmb
    INTEGER :: ii
    REAL :: tempb
    REAL :: tempb0
! EXECUTION
! Loop over all horseshoe vortices
    DO ii=1,n_vort
! Compute the magnitude of the force given by the 2D section
! L = 0.5*Vlocal²*area*cl
      CALL PUSHREAL4(cl)
      cl = cl0(ii) + alphalocal(ii)*cla(ii)
      CALL PUSHREAL4(vlocalm)
      CALL NORM(vlocal(:, ii), vlocalm)
      CALL PUSHREAL4(fairfm)
      fairfm = 0.5*rho*vlocalm*vlocalm*areas(ii)*cl
! Get normalized lift direction
      CALL PUSHREAL4ARRAY(li, 3)
      CALL CROSS(vlocal(:, ii), si(:, ii), li)
      CALL PUSHREAL4ARRAY(uli, 3)
      CALL NORMALIZE(li, uli)
! Store the force
      fairf(:, ii) = fairfm*uli
    END DO
    vlocalb = 0.0
    sib = 0.0
    areasb = 0.0
    alphalocalb = 0.0
    lib = 0.0
    DO ii=n_vort,1,-1
      ulib = 0.0
      fairfmb = SUM(uli*fairfb(:, ii))
      ulib = fairfm*fairfb(:, ii)
      fairfb(:, ii) = 0.0
      CALL POPREAL4ARRAY(uli, 3)
      CALL NORMALIZE_B(li, lib, uli, ulib)
      CALL POPREAL4ARRAY(li, 3)
      CALL CROSS_B(vlocal(:, ii), vlocalb(:, ii), si(:, ii), sib(:, ii)&
&            , li, lib)
      CALL POPREAL4(fairfm)
      tempb = rho*0.5*fairfmb
      vlocalmb = 2*vlocalm*areas(ii)*cl*tempb
      tempb0 = vlocalm**2*tempb
      areasb(ii) = areasb(ii) + cl*tempb0
      clb = areas(ii)*tempb0
      CALL POPREAL4(vlocalm)
      CALL NORM_B(vlocal(:, ii), vlocalb(:, ii), vlocalm, vlocalmb)
      CALL POPREAL4(cl)
      alphalocalb(ii) = alphalocalb(ii) + cla(ii)*clb
    END DO
  END SUBROUTINE COMPUTE_AIRFOIL_FORCES_B

!============================================================
  SUBROUTINE COMPUTE_AIRFOIL_FORCES(n_vort, rho, cl0, cla, areas, vlocal&
&   , alphalocal, si, fairf)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: rho, cl0(n_vort), cla(n_vort), areas(n_vort)
    REAL, INTENT(IN) :: vlocal(3, n_vort), alphalocal(n_vort), si(3, &
&   n_vort)
! Output variables
    REAL, INTENT(OUT) :: fairf(3, n_vort)
! Working variables
    REAL :: fairfm, cl, li(3), uli(3), vlocalm
    INTEGER :: ii
! EXECUTION
! Loop over all horseshoe vortices
    DO ii=1,n_vort
! Compute the magnitude of the force given by the 2D section
! L = 0.5*Vlocal²*area*cl
      cl = cl0(ii) + alphalocal(ii)*cla(ii)
      CALL NORM(vlocal(:, ii), vlocalm)
      fairfm = 0.5*rho*vlocalm*vlocalm*areas(ii)*cl
! Get normalized lift direction
      CALL CROSS(vlocal(:, ii), si(:, ii), li)
      CALL NORMALIZE(li, uli)
! Store the force
      fairf(:, ii) = fairfm*uli
    END DO
  END SUBROUTINE COMPUTE_AIRFOIL_FORCES

!  Differentiation of get_residuals in forward (tangent) mode:
!   variations   of useful results: res
!   with respect to varying inputs: alpha0 x gama
!============================================================
  SUBROUTINE GET_RESIDUALS_D(n_vort, x, xd, gama, gamad, alpha0, alpha0d&
&   , chords, cl0, cla, vinf, rho, res, resd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: xd(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), alpha0(n_vort)
    REAL, INTENT(IN) :: gamad(n_vort), alpha0d(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: res(n_vort)
    REAL, INTENT(OUT) :: resd(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: aicd(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: uaid(3, n_vort), unid(3, n_vort), sid(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: areasd(n_vort), vlocald(3, n_vort), alphalocald(n_vort)
    REAL :: fcirc(3, n_vort), fairf(3, n_vort), deltaf(3)
    REAL :: fcircd(3, n_vort), fairfd(3, n_vort), deltafd(3)
    INTRINSIC SUM
    REAL, DIMENSION(3) :: arg1
    REAL, DIMENSION(3) :: arg1d
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    CALL GET_AIC_MATRIX_D(n_vort, x, xd, uinf, aic, aicd)
! Get geometric vectors
    CALL GET_GEOM_VECTORS_D(n_vort, x, xd, alpha0, alpha0d, chords, uai&
&                     , uaid, uni, unid, si, sid, areas, areasd)
! Get induced velocities
    CALL GET_LOCAL_VELS_D(n_vort, gama, gamad, aic, aicd, vinf, uai, &
&                   uaid, uni, unid, vlocal, vlocald, alphalocal, &
&                   alphalocald)
! Get circulation forces
    CALL COMPUTE_CIRCULATION_FORCES_D(n_vort, rho, vlocal, vlocald, si, &
&                               sid, gama, gamad, fcirc, fcircd)
! Get airfoil forces
    CALL COMPUTE_AIRFOIL_FORCES_D(n_vort, rho, cl0, cla, areas, areasd, &
&                           vlocal, vlocald, alphalocal, alphalocald, si&
&                           , sid, fairf, fairfd)
    resd = 0.0
! The residual is the difference between the forces for each horseshoe vortex
    DO ii=1,n_vort
! Get the difference in forces
      deltafd = fcircd(:, ii) - fairfd(:, ii)
      deltaf = fcirc(:, ii) - fairf(:, ii)
! The residual is the magnitude of the difference
      arg1d(:) = 2*deltaf*deltafd
      arg1(:) = deltaf**2
      resd(ii) = SUM(arg1d(:))
      res(ii) = SUM(arg1(:))
    END DO
  END SUBROUTINE GET_RESIDUALS_D

!  Differentiation of get_residuals in reverse (adjoint) mode:
!   gradient     of useful results: res alpha0 x gama
!   with respect to varying inputs: alpha0 x gama
!============================================================
  SUBROUTINE GET_RESIDUALS_B(n_vort, x, xb, gama, gamab, alpha0, alpha0b&
&   , chords, cl0, cla, vinf, rho, res, resb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL :: xb(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), alpha0(n_vort)
    REAL :: gamab(n_vort), alpha0b(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL :: res(n_vort)
    REAL :: resb(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: aicb(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: uaib(3, n_vort), unib(3, n_vort), sib(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: areasb(n_vort), vlocalb(3, n_vort), alphalocalb(n_vort)
    REAL :: fcirc(3, n_vort), fairf(3, n_vort), deltaf(3)
    REAL :: fcircb(3, n_vort), fairfb(3, n_vort), deltafb(3)
    INTRINSIC SUM
    REAL, DIMENSION(3) :: arg1
    REAL, DIMENSION(3) :: arg1b
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    CALL GET_AIC_MATRIX(n_vort, x, uinf, aic)
! Get geometric vectors
    CALL PUSHREAL4ARRAY(uai, 3*n_vort)
    CALL GET_GEOM_VECTORS(n_vort, x, alpha0, chords, uai, uni, si, areas&
&                  )
! Get induced velocities
    CALL GET_LOCAL_VELS(n_vort, gama, aic, vinf, uai, uni, vlocal, &
&                 alphalocal)
! Get circulation forces
    CALL COMPUTE_CIRCULATION_FORCES(n_vort, rho, vlocal, si, gama, fcirc&
&                            )
! Get airfoil forces
    CALL COMPUTE_AIRFOIL_FORCES(n_vort, rho, cl0, cla, areas, vlocal, &
&                         alphalocal, si, fairf)
! The residual is the difference between the forces for each horseshoe vortex
    DO ii=1,n_vort
! Get the difference in forces
      CALL PUSHREAL4ARRAY(deltaf, 3)
      deltaf = fcirc(:, ii) - fairf(:, ii)
! The residual is the magnitude of the difference
      arg1(:) = deltaf**2
      res(ii) = SUM(arg1(:))
    END DO
    fairfb = 0.0
    fcircb = 0.0
    DO ii=n_vort,1,-1
      arg1b = 0.0
      arg1b(:) = resb(ii)
      resb(ii) = 0.0
      deltafb = 0.0
      deltafb = 2*deltaf*arg1b(:)
      CALL POPREAL4ARRAY(deltaf, 3)
      fcircb(:, ii) = fcircb(:, ii) + deltafb
      fairfb(:, ii) = fairfb(:, ii) - deltafb
    END DO
    CALL COMPUTE_AIRFOIL_FORCES_B(n_vort, rho, cl0, cla, areas, areasb, &
&                           vlocal, vlocalb, alphalocal, alphalocalb, si&
&                           , sib, fairf, fairfb)
    CALL COMPUTE_CIRCULATION_FORCES_B(n_vort, rho, vlocal, vlocalb, si, &
&                               sib, gama, gamab, fcirc, fcircb)
    CALL GET_LOCAL_VELS_B(n_vort, gama, gamab, aic, aicb, vinf, uai, &
&                   uaib, uni, unib, vlocal, vlocalb, alphalocal, &
&                   alphalocalb)
    CALL POPREAL4ARRAY(uai, 3*n_vort)
    CALL GET_GEOM_VECTORS_B(n_vort, x, xb, alpha0, alpha0b, chords, uai&
&                     , uaib, uni, unib, si, sib, areas, areasb)
    CALL GET_AIC_MATRIX_B(n_vort, x, xb, uinf, aic, aicb)
  END SUBROUTINE GET_RESIDUALS_B

!============================================================
  SUBROUTINE GET_RESIDUALS(n_vort, x, gama, alpha0, chords, cl0, cla, &
&   vinf, rho, res)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), alpha0(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: res(n_vort)
! Working variables
    INTEGER :: ii
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: fcirc(3, n_vort), fairf(3, n_vort), deltaf(3)
    INTRINSIC SUM
    REAL, DIMENSION(3) :: arg1
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    CALL GET_AIC_MATRIX(n_vort, x, uinf, aic)
! Get geometric vectors
    CALL GET_GEOM_VECTORS(n_vort, x, alpha0, chords, uai, uni, si, areas&
&                  )
! Get induced velocities
    CALL GET_LOCAL_VELS(n_vort, gama, aic, vinf, uai, uni, vlocal, &
&                 alphalocal)
! Get circulation forces
    CALL COMPUTE_CIRCULATION_FORCES(n_vort, rho, vlocal, si, gama, fcirc&
&                            )
! Get airfoil forces
    CALL COMPUTE_AIRFOIL_FORCES(n_vort, rho, cl0, cla, areas, vlocal, &
&                         alphalocal, si, fairf)
! The residual is the difference between the forces for each horseshoe vortex
    DO ii=1,n_vort
! Get the difference in forces
      deltaf = fcirc(:, ii) - fairf(:, ii)
! The residual is the magnitude of the difference
      arg1(:) = deltaf**2
      res(ii) = SUM(arg1(:))
    END DO
  END SUBROUTINE GET_RESIDUALS

!  Differentiation of get_functions in forward (tangent) mode:
!   variations   of useful results: d loads l sref
!   with respect to varying inputs: alpha0 x gama
!============================================================
  SUBROUTINE GET_FUNCTIONS_D(n_vort, x, xd, gama, gamad, alpha0, alpha0d&
&   , chords, cl0, cla, vinf, rho, sref, srefd, cl, cd, l, ld, d, dd, &
&   loads, loadsd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: xd(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), alpha0(n_vort)
    REAL, INTENT(IN) :: gamad(n_vort), alpha0d(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: sref, cl, cd, l, d, loads(n_vort)
    REAL, INTENT(OUT) :: srefd, ld, dd, loadsd(n_vort)
! Working variables
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: uinfd(3), aicd(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: uaid(3, n_vort), unid(3, n_vort), sid(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: areasd(n_vort), vlocald(3, n_vort), alphalocald(n_vort)
    REAL :: fcirc(3, n_vort), fbody(3), fbodym, vinfm
    REAL :: fcircd(3, n_vort), fbodyd(3), fbodymd
    INTRINSIC SUM
    INTRINSIC SQRT
    REAL :: arg1
    REAL :: arg1d
    REAL :: temp
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    CALL GET_AIC_MATRIX_D(n_vort, x, xd, uinf, aic, aicd)
! Get geometric vectors
    CALL GET_GEOM_VECTORS_D(n_vort, x, xd, alpha0, alpha0d, chords, uai&
&                     , uaid, uni, unid, si, sid, areas, areasd)
! Get induced velocities
    unid = 0.0
    uaid = 0.0
    CALL GET_LOCAL_VELS_D(n_vort, gama, gamad, aic, aicd, vinf, uai, &
&                   uaid, uni, unid, vlocal, vlocald, alphalocal, &
&                   alphalocald)
! Get forces on every bound vortex
    CALL COMPUTE_CIRCULATION_FORCES_D(n_vort, rho, vlocal, vlocald, si, &
&                               sid, gama, gamad, fcirc, fcircd)
! Store bending forces
    loadsd = fcircd(3, :)
    loads = fcirc(3, :)
! Get total force in the system of coordinates of the body
    fbodyd = 0.0
    fbodyd(1) = SUM(fcircd(1, :))
    fbody(1) = SUM(fcirc(1, :))
    fbodyd(2) = SUM(fcircd(2, :))
    fbody(2) = SUM(fcirc(2, :))
    fbodyd(3) = SUM(fcircd(3, :))
    fbody(3) = SUM(fcirc(3, :))
! The drag is aligned with the free-stream
    uinfd = 0.0
    CALL DOT_D(fbody, fbodyd, uinf, uinfd, d, dd)
! The rest is the lift force
    CALL NORM_D(fbody, fbodyd, fbodym, fbodymd)
    arg1d = 2*fbodym*fbodymd - 2*d*dd
    arg1 = fbodym*fbodym - d*d
    temp = SQRT(arg1)
    IF (arg1 .EQ. 0.0) THEN
      ld = 0.0
    ELSE
      ld = arg1d/(2.0*temp)
    END IF
    l = temp
! Use the total area as reference
    srefd = SUM(areasd)
    sref = SUM(areas)
! Make results non dimensional
    CALL NORM(vinf, vinfm)
    cl = 2.0*l/sref/vinfm/vinfm/rho
    cd = 2.0*d/sref/vinfm/vinfm/rho
  END SUBROUTINE GET_FUNCTIONS_D

!  Differentiation of get_functions in reverse (adjoint) mode:
!   gradient     of useful results: d loads l x sref
!   with respect to varying inputs: alpha0 x gama
!============================================================
  SUBROUTINE GET_FUNCTIONS_B(n_vort, x, xb, gama, gamab, alpha0, alpha0b&
&   , chords, cl0, cla, vinf, rho, sref, srefb, cl, cd, l, lb, d, db, &
&   loads, loadsb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL :: xb(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), alpha0(n_vort)
    REAL :: gamab(n_vort), alpha0b(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL :: sref, cl, cd, l, d, loads(n_vort)
    REAL :: srefb, lb, db, loadsb(n_vort)
! Working variables
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: uinfb(3), aicb(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: uaib(3, n_vort), unib(3, n_vort), sib(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: areasb(n_vort), vlocalb(3, n_vort), alphalocalb(n_vort)
    REAL :: fcirc(3, n_vort), fbody(3), fbodym, vinfm
    REAL :: fcircb(3, n_vort), fbodyb(3), fbodymb
    INTRINSIC SUM
    INTRINSIC SQRT
    REAL :: arg1
    REAL :: arg1b
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    CALL GET_AIC_MATRIX(n_vort, x, uinf, aic)
! Get geometric vectors
    CALL PUSHREAL4ARRAY(uai, 3*n_vort)
    CALL GET_GEOM_VECTORS(n_vort, x, alpha0, chords, uai, uni, si, areas&
&                  )
! Get induced velocities
    CALL GET_LOCAL_VELS(n_vort, gama, aic, vinf, uai, uni, vlocal, &
&                 alphalocal)
! Get forces on every bound vortex
    CALL COMPUTE_CIRCULATION_FORCES(n_vort, rho, vlocal, si, gama, fcirc&
&                            )
! Store bending forces
    loads = fcirc(3, :)
! Get total force in the system of coordinates of the body
    fbody(1) = SUM(fcirc(1, :))
    fbody(2) = SUM(fcirc(2, :))
    fbody(3) = SUM(fcirc(3, :))
! The drag is aligned with the free-stream
    CALL DOT(fbody, uinf, d)
! The rest is the lift force
    CALL NORM(fbody, fbodym)
    arg1 = fbodym*fbodym - d*d
    l = SQRT(arg1)
! Use the total area as reference
    sref = SUM(areas)
! Make results non dimensional
    CALL NORM(vinf, vinfm)
    cl = 2.0*l/sref/vinfm/vinfm/rho
    cd = 2.0*d/sref/vinfm/vinfm/rho
    areasb = 0.0
    areasb = srefb
    IF (arg1 .EQ. 0.0) THEN
      arg1b = 0.0
    ELSE
      arg1b = lb/(2.0*SQRT(arg1))
    END IF
    fbodymb = 2*fbodym*arg1b
    db = db - 2*d*arg1b
    fbodyb = 0.0
    CALL NORM_B(fbody, fbodyb, fbodym, fbodymb)
    uinfb = 0.0
    CALL DOT_B(fbody, fbodyb, uinf, uinfb, d, db)
    fcircb = 0.0
    fcircb(3, :) = fcircb(3, :) + fbodyb(3) + loadsb
    fbodyb(3) = 0.0
    fcircb(2, :) = fcircb(2, :) + fbodyb(2)
    fbodyb(2) = 0.0
    fcircb(1, :) = fcircb(1, :) + fbodyb(1)
    vlocalb = 0.0
    sib = 0.0
    gamab = 0.0
    CALL COMPUTE_CIRCULATION_FORCES_B(n_vort, rho, vlocal, vlocalb, si, &
&                               sib, gama, gamab, fcirc, fcircb)
    alphalocalb = 0.0
    CALL GET_LOCAL_VELS_B(n_vort, gama, gamab, aic, aicb, vinf, uai, &
&                   uaib, uni, unib, vlocal, vlocalb, alphalocal, &
&                   alphalocalb)
    CALL POPREAL4ARRAY(uai, 3*n_vort)
    alpha0b = 0.0
    uaib = 0.0
    unib = 0.0
    CALL GET_GEOM_VECTORS_B(n_vort, x, xb, alpha0, alpha0b, chords, uai&
&                     , uaib, uni, unib, si, sib, areas, areasb)
    CALL GET_AIC_MATRIX_B(n_vort, x, xb, uinf, aic, aicb)
  END SUBROUTINE GET_FUNCTIONS_B

!============================================================
  SUBROUTINE GET_FUNCTIONS(n_vort, x, gama, alpha0, chords, cl0, cla, &
&   vinf, rho, sref, cl, cd, l, d, loads)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), alpha0(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: sref, cl, cd, l, d, loads(n_vort)
! Working variables
    REAL :: uinf(3), aic(3, n_vort, n_vort)
    REAL :: uai(3, n_vort), uni(3, n_vort), si(3, n_vort)
    REAL :: areas(n_vort), vlocal(3, n_vort), alphalocal(n_vort)
    REAL :: fcirc(3, n_vort), fbody(3), fbodym, vinfm
    INTRINSIC SUM
    INTRINSIC SQRT
    REAL :: arg1
! EXECUTION
! Normalize free-stream velocity
    CALL NORMALIZE(vinf, uinf)
! Get AIC matrix
    CALL GET_AIC_MATRIX(n_vort, x, uinf, aic)
! Get geometric vectors
    CALL GET_GEOM_VECTORS(n_vort, x, alpha0, chords, uai, uni, si, areas&
&                  )
! Get induced velocities
    CALL GET_LOCAL_VELS(n_vort, gama, aic, vinf, uai, uni, vlocal, &
&                 alphalocal)
! Get forces on every bound vortex
    CALL COMPUTE_CIRCULATION_FORCES(n_vort, rho, vlocal, si, gama, fcirc&
&                            )
! Store bending forces
    loads = fcirc(3, :)
! Get total force in the system of coordinates of the body
    fbody(1) = SUM(fcirc(1, :))
    fbody(2) = SUM(fcirc(2, :))
    fbody(3) = SUM(fcirc(3, :))
! The drag is aligned with the free-stream
    CALL DOT(fbody, uinf, d)
! The rest is the lift force
    CALL NORM(fbody, fbodym)
    arg1 = fbodym*fbodym - d*d
    l = SQRT(arg1)
! Use the total area as reference
    sref = SUM(areas)
! Make results non dimensional
    CALL NORM(vinf, vinfm)
    cl = 2.0*l/sref/vinfm/vinfm/rho
    cd = 2.0*d/sref/vinfm/vinfm/rho
  END SUBROUTINE GET_FUNCTIONS

!  Differentiation of norm in forward (tangent) mode:
!   variations   of useful results: am
!   with respect to varying inputs: a
!============================================================
  SUBROUTINE NORM_D(a, ad, am, amd)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL, INTENT(IN) :: ad(3)
    REAL, INTENT(OUT) :: am
    REAL, INTENT(OUT) :: amd
    INTRINSIC SQRT
    REAL :: arg1
    REAL :: arg1d
    REAL :: temp
    arg1d = 2*a(1)*ad(1) + 2*a(2)*ad(2) + 2*a(3)*ad(3)
    arg1 = a(1)*a(1) + a(2)*a(2) + a(3)*a(3)
    temp = SQRT(arg1)
    IF (arg1 .EQ. 0.0) THEN
      amd = 0.0
    ELSE
      amd = arg1d/(2.0*temp)
    END IF
    am = temp
  END SUBROUTINE NORM_D

!  Differentiation of norm in reverse (adjoint) mode:
!   gradient     of useful results: am a
!   with respect to varying inputs: a
!============================================================
  SUBROUTINE NORM_B(a, ab, am, amb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL :: ab(3)
    REAL :: am
    REAL :: amb
    INTRINSIC SQRT
    REAL :: arg1
    REAL :: arg1b
    arg1 = a(1)*a(1) + a(2)*a(2) + a(3)*a(3)
    CALL PUSHREAL4(am)
    am = SQRT(arg1)
    CALL POPREAL4(am)
    IF (arg1 .EQ. 0.0) THEN
      arg1b = 0.0
    ELSE
      arg1b = amb/(2.0*SQRT(arg1))
    END IF
    ab(1) = ab(1) + 2*a(1)*arg1b
    ab(2) = ab(2) + 2*a(2)*arg1b
    ab(3) = ab(3) + 2*a(3)*arg1b
  END SUBROUTINE NORM_B

!============================================================
  SUBROUTINE NORM(a, am)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL, INTENT(OUT) :: am
    INTRINSIC SQRT
    REAL :: arg1
    arg1 = a(1)*a(1) + a(2)*a(2) + a(3)*a(3)
    am = SQRT(arg1)
  END SUBROUTINE NORM

!  Differentiation of normalize in forward (tangent) mode:
!   variations   of useful results: an
!   with respect to varying inputs: a
!============================================================
  SUBROUTINE NORMALIZE_D(a, ad, an, and)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL, INTENT(IN) :: ad(3)
    REAL, INTENT(OUT) :: an(3)
    REAL, INTENT(OUT) :: and(3)
    REAL :: am
    REAL :: amd
    CALL NORM_D(a, ad, am, amd)
    and = (ad-a*amd/am)/am
    an = a/am
  END SUBROUTINE NORMALIZE_D

!  Differentiation of normalize in reverse (adjoint) mode:
!   gradient     of useful results: an a
!   with respect to varying inputs: a
!============================================================
  SUBROUTINE NORMALIZE_B(a, ab, an, anb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL :: ab(3)
    REAL :: an(3)
    REAL :: anb(3)
    REAL :: am
    REAL :: amb
    CALL NORM(a, am)
    CALL PUSHREAL4ARRAY(an, 3)
    an = a/am
    CALL POPREAL4ARRAY(an, 3)
    ab = ab + anb/am
    amb = -(SUM(a*anb)/am**2)
    CALL NORM_B(a, ab, am, amb)
  END SUBROUTINE NORMALIZE_B

!============================================================
  SUBROUTINE NORMALIZE(a, an)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3)
    REAL, INTENT(OUT) :: an(3)
    REAL :: am
    CALL NORM(a, am)
    an = a/am
  END SUBROUTINE NORMALIZE

!  Differentiation of dot in forward (tangent) mode:
!   variations   of useful results: adb
!   with respect to varying inputs: a b
!============================================================
  SUBROUTINE DOT_D(a, ad, b, bd, adb, adbd)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL, INTENT(IN) :: ad(3), bd(3)
    REAL, INTENT(OUT) :: adb
    REAL, INTENT(OUT) :: adbd
    INTRINSIC SUM
    adbd = SUM(b*ad + a*bd)
    adb = SUM(a*b)
  END SUBROUTINE DOT_D

!  Differentiation of dot in reverse (adjoint) mode:
!   gradient     of useful results: adb a b
!   with respect to varying inputs: a b
!============================================================
  SUBROUTINE DOT_B(a, ab, b, bb, adb, adbb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL :: ab(3), bb(3)
    REAL :: adb
    REAL :: adbb
    INTRINSIC SUM
    CALL PUSHREAL4(adb)
    adb = SUM(a*b)
    CALL POPREAL4(adb)
    ab = ab + b*adbb
    bb = bb + a*adbb
  END SUBROUTINE DOT_B

!============================================================
  SUBROUTINE DOT(a, b, adb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL, INTENT(OUT) :: adb
    INTRINSIC SUM
    adb = SUM(a*b)
  END SUBROUTINE DOT

!  Differentiation of cross in forward (tangent) mode:
!   variations   of useful results: acb
!   with respect to varying inputs: acb a b
!============================================================
  SUBROUTINE CROSS_D(a, ad, b, bd, acb, acbd)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL, INTENT(IN) :: ad(3), bd(3)
    REAL, INTENT(OUT) :: acb(3)
    REAL, INTENT(OUT) :: acbd(3)
    acbd(1) = b(3)*ad(2) + a(2)*bd(3) - b(2)*ad(3) - a(3)*bd(2)
    acb(1) = a(2)*b(3) - a(3)*b(2)
    acbd(2) = b(1)*ad(3) + a(3)*bd(1) - b(3)*ad(1) - a(1)*bd(3)
    acb(2) = a(3)*b(1) - a(1)*b(3)
    acbd(3) = b(2)*ad(1) + a(1)*bd(2) - b(1)*ad(2) - a(2)*bd(1)
    acb(3) = a(1)*b(2) - a(2)*b(1)
  END SUBROUTINE CROSS_D

!  Differentiation of cross in reverse (adjoint) mode:
!   gradient     of useful results: acb a b
!   with respect to varying inputs: acb a b
!============================================================
  SUBROUTINE CROSS_B(a, ab, b, bb, acb, acbb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL :: ab(3), bb(3)
    REAL :: acb(3)
    REAL :: acbb(3)
    CALL PUSHREAL4(acb(1))
    acb(1) = a(2)*b(3) - a(3)*b(2)
    CALL PUSHREAL4(acb(2))
    acb(2) = a(3)*b(1) - a(1)*b(3)
    CALL PUSHREAL4(acb(3))
    acb(3) = a(1)*b(2) - a(2)*b(1)
    CALL POPREAL4(acb(3))
    ab(1) = ab(1) + b(2)*acbb(3) - b(3)*acbb(2)
    bb(2) = bb(2) + a(1)*acbb(3) - a(3)*acbb(1)
    ab(2) = ab(2) + b(3)*acbb(1) - b(1)*acbb(3)
    bb(1) = bb(1) + a(3)*acbb(2) - a(2)*acbb(3)
    acbb(3) = 0.0
    CALL POPREAL4(acb(2))
    ab(3) = ab(3) + b(1)*acbb(2) - b(2)*acbb(1)
    bb(3) = bb(3) + a(2)*acbb(1) - a(1)*acbb(2)
    acbb(2) = 0.0
    CALL POPREAL4(acb(1))
    acbb(1) = 0.0
  END SUBROUTINE CROSS_B

!============================================================
  SUBROUTINE CROSS(a, b, acb)
    IMPLICIT NONE
    REAL, INTENT(IN) :: a(3), b(3)
    REAL, INTENT(OUT) :: acb(3)
    acb(1) = a(2)*b(3) - a(3)*b(2)
    acb(2) = a(3)*b(1) - a(1)*b(3)
    acb(3) = a(1)*b(2) - a(2)*b(1)
  END SUBROUTINE CROSS

!  Differentiation of tapenade_main in forward (tangent) mode:
!   variations   of useful results: d res loads l sref
!   with respect to varying inputs: alpha0 x gama
!============================================================
  SUBROUTINE TAPENADE_MAIN_D(n_vort, x, xd, gama, gamad, alpha0, alpha0d&
&   , chords, cl0, cla, vinf, rho, res, resd, sref, srefd, cl, cd, l, ld&
&   , d, dd, loads, loadsd)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: xd(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), alpha0(n_vort)
    REAL, INTENT(IN) :: gamad(n_vort), alpha0d(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: res(n_vort), sref, cl, cd, l, d
    REAL, INTENT(OUT) :: resd(n_vort), srefd, ld, dd
    REAL, INTENT(OUT) :: loads(n_vort)
    REAL, INTENT(OUT) :: loadsd(n_vort)
! EXECUTION
! Call relevant subroutines
    CALL GET_RESIDUALS_D(n_vort, x, xd, gama, gamad, alpha0, alpha0d, &
&                  chords, cl0, cla, vinf, rho, res, resd)
    CALL GET_FUNCTIONS_D(n_vort, x, xd, gama, gamad, alpha0, alpha0d, &
&                  chords, cl0, cla, vinf, rho, sref, srefd, cl, cd, l, &
&                  ld, d, dd, loads, loadsd)
  END SUBROUTINE TAPENADE_MAIN_D

!  Differentiation of tapenade_main in reverse (adjoint) mode:
!   gradient     of useful results: d res loads l x sref
!   with respect to varying inputs: alpha0 x gama
!============================================================
  SUBROUTINE TAPENADE_MAIN_B(n_vort, x, xb, gama, gamab, alpha0, alpha0b&
&   , chords, cl0, cla, vinf, rho, res, resb, sref, srefb, cl, cd, l, lb&
&   , d, db, loads, loadsb)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL :: xb(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), alpha0(n_vort)
    REAL :: gamab(n_vort), alpha0b(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL :: res(n_vort), sref, cl, cd, l, d
    REAL :: resb(n_vort), srefb, lb, db
    REAL :: loads(n_vort)
    REAL :: loadsb(n_vort)
! EXECUTION
! Call relevant subroutines
    CALL GET_RESIDUALS(n_vort, x, gama, alpha0, chords, cl0, cla, vinf, &
&                rho, res)
    CALL GET_FUNCTIONS(n_vort, x, gama, alpha0, chords, cl0, cla, vinf, &
&                rho, sref, cl, cd, l, d, loads)
    CALL GET_FUNCTIONS_B(n_vort, x, xb, gama, gamab, alpha0, alpha0b, &
&                  chords, cl0, cla, vinf, rho, sref, srefb, cl, cd, l, &
&                  lb, d, db, loads, loadsb)
    CALL GET_RESIDUALS_B(n_vort, x, xb, gama, gamab, alpha0, alpha0b, &
&                  chords, cl0, cla, vinf, rho, res, resb)
  END SUBROUTINE TAPENADE_MAIN_B

!============================================================
  SUBROUTINE TAPENADE_MAIN(n_vort, x, gama, alpha0, chords, cl0, cla, &
&   vinf, rho, res, sref, cl, cd, l, d, loads)
    IMPLICIT NONE
! Input variables
    INTEGER, INTENT(IN) :: n_vort
    REAL, INTENT(IN) :: x(3, n_vort+1)
    REAL, INTENT(IN) :: gama(n_vort), alpha0(n_vort)
    REAL, INTENT(IN) :: chords(n_vort), cl0(n_vort)
    REAL, INTENT(IN) :: cla(n_vort), vinf(3), rho
! Output variables
    REAL, INTENT(OUT) :: res(n_vort), sref, cl, cd, l, d
    REAL, INTENT(OUT) :: loads(n_vort)
! EXECUTION
! Call relevant subroutines
    CALL GET_RESIDUALS(n_vort, x, gama, alpha0, chords, cl0, cla, vinf, &
&                rho, res)
    CALL GET_FUNCTIONS(n_vort, x, gama, alpha0, chords, cl0, cla, vinf, &
&                rho, sref, cl, cd, l, d, loads)
  END SUBROUTINE TAPENADE_MAIN

END MODULE LLT_MODULE_DIFF

